services:
  rag-backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PIP_INDEX_URL: https://pypi.tuna.tsinghua.edu.cn/simple
    container_name: rag-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - config/.env
    volumes:
      - ./data:/app/data
      - ./models:/app/models
